# Generated by Django 4.1 on 2022-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('phoneNo', models.CharField(max_length=20)),
                ('Language', models.CharField(max_length=30)),
                ('DoM', models.CharField(max_length=30)),
                ('DoR', models.CharField(max_length=30)),
                ('DoIns', models.CharField(max_length=30)),
                ('ChassisNo', models.CharField(max_length=30)),
                ('modelNo', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
