# Generated by Django 4.1 on 2022-08-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_registration_age_registration_insduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Age',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='registration',
            name='InsDuration',
            field=models.CharField(max_length=4),
        ),
    ]
