# Generated by Django 4.1 on 2022-08-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_registration_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Ticket', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('Time', models.CharField(max_length=30)),
                ('VID', models.CharField(max_length=30)),
                ('Progress', models.CharField(max_length=30)),
            ],
        ),
    ]
