# Generated by Django 4.1 on 2022-09-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
