# Generated by Django 4.1 on 2022-12-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_complaints_complaint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='complaint_id',
        ),
    ]
